In [ ]:
#1

import numpy as np


arr = np.array([3, 5, 9, 16, 25])


arr_float = arr.astype(float)

print(arr_float)

[ 3.  5.  9. 16. 25.]


In [ ]:
#2
import numpy as np


arr = np.array([1.2, -3.6, 8.99999, 16.1])


arr_int = arr.astype(int)

print(arr_int)



[ 1 -3  8 16]


In [ ]:
#3
import numpy as np


matriz_zeros = np.zeros((3, 9))

print(matriz_zeros)



[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#4
import numpy as np


matriz_uns = np.ones((6, 7), dtype=int)

print(matriz_uns)



[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [6]:
#5
import numpy as np


matriz_identidade = np.eye(4, dtype=int)

print(matriz_identidade)


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [7]:
6#
import numpy as np


array_aleatorio = np.random.rand(5)

print(array_aleatorio)




[0.98390516 0.6479053  0.46772207 0.96040133 0.10616364]


In [8]:
#7
import numpy as np


matriz_aleatoria = np.random.randint(0, 6, (3, 6))

print(matriz_aleatoria)




[[4 5 3 0 4 2]
 [2 3 4 2 3 3]
 [2 2 1 1 0 1]]


In [9]:
#8
import numpy as np


matriz = np.array([[4, 6, 8],
                   [-4, 3, 2],
                   [22, -15, 12]])


valor_maximo = np.max(matriz)

print("O valor máximo da matriz é:", valor_maximo)



O valor máximo da matriz é: 22


In [10]:
#9
import numpy as np


matriz = np.array([[4, 6, 8],
                   [-4, 3, 2],
                   [22, -15, 12]])


valor_minimo = np.min(matriz)

print("O valor mínimo da matriz é:", valor_minimo)



O valor mínimo da matriz é: -15


In [11]:
#10
import numpy as np


matriz = np.array([[4, 6, 8],
                   [-4, 3, 2],
                   [22, -15, 12]])


soma_total = np.sum(matriz)

print("A soma de todos os elementos da matriz é:", soma_total)



A soma de todos os elementos da matriz é: 38


In [12]:
#11
import numpy as np


array = np.array([13, -2, 6, 8, 23, 15, 3, 90, 4, 10, 56, 12])


media = np.mean(array)

print("A média dos elementos do array é:", media)




A média dos elementos do array é: 19.833333333333332


In [13]:
#12
import numpy as np


array = np.array([13, -2, 6, 8, 23, 15, 3, 90, 4, 10, 56, 12])


quarto_elemento = array[3]

print("O 4º elemento do array é:", quarto_elemento)



O 4º elemento do array é: 8


In [14]:
#13
import numpy as np


array = np.array([13, -2, 6, 8, 23, 15, 3, 90, 4, 10, 56, 12])


ultimos_elementos = array[-3:]

print("Os 3 últimos elementos do array são:", ultimos_elementos)



Os 3 últimos elementos do array são: [10 56 12]


In [16]:
#14
import numpy as np


array = np.array([13, -2, 6, 8, 23, 15, 3, 90, 4, 10, 56, 12])


elementos_a_partir_da_posicao_2 = array[2:]

print("Os elementos a partir da posição 2 são:", elementos_a_partir_da_posicao_2)



Os elementos a partir da posição 2 são: [ 6  8 23 15  3 90  4 10 56 12]


In [25]:
#15
import numpy as np


array = np.array([13, -2, 6, 8, 23, 15, 3, 90, 4, 10, 56, 12])


elementos_entre_2_e_6 = array[1:6]

print("Os elementos entre o 2º e o 6º (inclusive) são:", elementos_entre_2_e_6)


Os elementos entre o 2º e o 6º (inclusive) são: [-2  6  8 23 15]


In [31]:
#16
import numpy as np

matriz = np.array([[ 1,  3,  16, -25,  14],
                   [ 2,  0,  10,   5,  17],
                   [19,  4,   8,  15,  13],
                   [ 7, 12,  -5,  14,   0]])


resultado = np.array([23, 15, 3, 90])

print("O array desejado é:", resultado)






O array desejado é: [23 15  3 90]


In [32]:
#17
import numpy as np


matriz = np.array([[1, 3, 16, -25, 14],
                   [2, 0, 10, 5, 17],
                   [19, 4, 8, 15, 13],
                   [7, 12, -5, 14, 0]])


terceira_linha = matriz[2]

print("A 3ª linha da matriz é:", terceira_linha)


A 3ª linha da matriz é: [19  4  8 15 13]


In [33]:
#18
import numpy as np


matriz = np.array([[1, 3, 16, -25, 14],
                   [2, 0, 10, 5, 17],
                   [19, 4, 8, 15, 13],
                   [7, 12, -5, 14, 0]])


quarta_coluna = matriz[:, 3]

print("A 4ª coluna da matriz é:", quarta_coluna)


A 4ª coluna da matriz é: [-25   5  15  14]


In [34]:
#19
import numpy as np


matriz = np.array([[1, 3, 16, -25, 14],
                   [2, 0, 10, 5, 17],
                   [19, 4, 8, 15, 13],
                   [7, 12, -5, 14, 0]])


elemento_10 = matriz[1, 2]

print("O elemento de valor 10 é:", elemento_10)


O elemento de valor 10 é: 10


In [35]:
#20
import numpy as np


matriz = np.array([[0, 10, 5],
                   [4, 8, 15]])


print("A matriz é:")
print(matriz)


A matriz é:
[[ 0 10  5]
 [ 4  8 15]]


In [36]:
#21
import numpy as np


matriz = np.array([[2, -1, 15, 24],
                   [-3, 18, 4, 25],
                   [9, 10, -13, 7]])


nova_matriz = np.where(matriz % 2 == 0, 2, 1)


print("A nova matriz é:")
print(nova_matriz)


A nova matriz é:
[[2 1 1 2]
 [1 2 2 1]
 [1 2 1 1]]
